export enum Cmd {
    PACKET_UNKNOWN = 0x80,
    PACKET_IS_SOCKET_ALIVE = 0x81,
    PACKET_HELLO_ACK = 0x82,
    PACKET_HISTORY_DATA = 0x83,
    ARRIVAL_HISTORY_DATA = 0x84,
    PACKET_VERIFY_DATA = 0x85,
    PACKET_NEW_DATA = 0x86,
    PACKET_OTA_INFO = 0x87,
    PACKET_OTA_SLICE= 0x88,
    PACKET_RAW_DATA = 0x90,
    ARRIVAL_RAW_DATA = 0x91
}